---
title: "R Notebook"
output: html_notebook
---


```{r}
weight=read.csv("C:\\Users\\agelf\\Documents\\School\\U of C\\Masters of Data Science and Analytics\\Data 603\\Group Project\\weight_change_dataset.csv")
colnames(weight)
```

Full model:

```{r}
weight_model_full=lm(Weight.Change..lbs.~Age+factor(Gender)+Current.Weight..lbs.+BMR..Calories.+Daily.Calories.Consumed+Daily.Caloric.Surplus.Deficit+Duration..weeks.+factor(Physical.Activity.Level)+factor(Sleep.Quality)+factor(Stress.Level)+Final.Weight..lbs., data=weight)
summary(weight_model_full)
```

```{r}
weight_model_take2=lm(Weight.Change..lbs.~Age+factor(Gender)+BMR..Calories.+Daily.Calories.Consumed+Daily.Caloric.Surplus.Deficit+Duration..weeks.+factor(Physical.Activity.Level)+factor(Sleep.Quality)+factor(Stress.Level), data=weight)
summary(weight_model_take2)
```

```{r}
library(olsrr)
```


```{r}
weight_model_step=lm(Weight.Change..lbs.~Age+Gender+BMR..Calories.+Daily.Calories.Consumed+Daily.Caloric.Surplus.Deficit+Duration..weeks.+Physical.Activity.Level+Sleep.Quality+Stress.Level, data=weight)
weight_step=ols_step_both_p(weight_model_step,p_enter = 0.05, p_remove = 0.06, details=TRUE)
summary(weight_step$model)
```

```{r}
weight_model_take3=lm(Weight.Change..lbs.~BMR..Calories.+factor(Sleep.Quality)+Duration..weeks.+factor(Stress.Level), data=weight)
summary(weight_model_take3)
```

```{r}
weight2=weight
```


```{r}
weight2$Gender=as.factor(weight2$Gender)
weight2$Physical.Activity.Level=as.factor(weight2$Physical.Activity.Level)
weight2$Sleep.Quality=as.factor(weight2$Sleep.Quality)
weight2$Stress.Level=as.factor(weight2$Stress.Level)
```

```{r}
weight_model_take4=lm(Weight.Change..lbs.~Age+Gender+BMR..Calories.+Daily.Calories.Consumed+Daily.Caloric.Surplus.Deficit+Duration..weeks.+Physical.Activity.Level+Sleep.Quality+Stress.Level, data=weight2)
summary(weight_model_take4)
```

```{r}
weight_step2=ols_step_both_p(weight_model_take4,p_enter = 0.05, p_remove = 0.06, details=TRUE)
summary(weight_step2$model)
```

```{r}
weight_take5=lm(Weight.Change..lbs.~Sleep.Quality+Stress.Level+Duration..weeks.+Daily.Caloric.Surplus.Deficit,data=weight2)
summary(weight_take5)
```

Use the figures
```{r}
library(GGally)
```

```{r}
weightfigs = data.frame(weight2$Weight.Change..lbs.,weight2$Sleep.Quality,weight2$Stress.Level,weight2$Duration..weeks.,weight2$Daily.Caloric.Surplus.Deficit)
#LOESS or LOWESS: LOcally WEighted Scatter-plot Smoother
ggpairs(weightfigs,lower = list(continuous = "smooth_loess", combo = "facethist", discrete = "facetbar", na = "na"))
#pairs(~Y+X1+X2+factor(X3)+X4+X5,data=salary,panel = panel.smooth) 
```


```{r}
weight_take5_int=lm(Weight.Change..lbs.~(Sleep.Quality+Stress.Level+Duration..weeks.+Daily.Caloric.Surplus.Deficit)^2,data=weight2)
summary(weight_take5_int)
```
```{r}
weight_take5_int_reduced=lm(Weight.Change..lbs.~Sleep.Quality + Stress.Level + Duration..weeks. + Daily.Caloric.Surplus.Deficit + Sleep.Quality*Stress.Level + Stress.Level*Duration..weeks. + Stress.Level*Daily.Caloric.Surplus.Deficit,data=weight2)
summary(weight_take5_int_reduced)
```
```{r}
anova(weight_take5_int_reduced,weight_take5_int)
```

```{r}
anova(weight_take5_int_reduced,weight_take5)
```

