---
title: "Project603"
author: "Venkateshwaran"
date: "2024-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
title: "R Notebook"
output: html_notebook
---

To determine the best model for predicting weight change, given our dataset, we begin by uploading the data set.
```{r}
weight=read.csv("C:\\Users\\Venkateshwaran\\OneDrive\\Desktop\\Data603_FinalProject\\Data-603-Group-Project\\weight_change_dataset.csv")
colnames(weight)
```
We then make sure all libraries neaded are uploaded
```{r}
library(GGally)
library(mctest)
library(car)
library(ggplot2)
library(Ecdat)
library(lmtest)
```
```{r}
weight_model_full=lm(Weight.Change..lbs. ~ Age + Gender + Daily.Caloric.Surplus.Deficit + Duration..weeks. + Physical.Activity.Level + Sleep.Quality + Stress.Level, data=weight)
summary(weight_model_full)
```
```{r}
stepmod=ols_step_both_p(weight_model_full,details=TRUE)
```

```{r}
ExecSubsets=ols_step_best_subset(weight_model_full, details=TRUE) # for the output interpretation 
ExecSubsets$metrics
```

```{r}
rsquare=c((ExecSubsets$metrics)$rsquare) 
AdjustedR=c((ExecSubsets$metrics)$adjr)
cp=c((ExecSubsets$metrics)$cp) 
AIC=c((ExecSubsets$metrics)$aic) 
cbind(rsquare,AdjustedR,cp,AIC)
```
```{r}
par(mfrow=c(2,2)) # split the plotting panel into a 2 x 2 grid 
plot(cp,type = "o",pch=10, xlab="Number of Variables",ylab= "Cp") 
plot(rsquare,type = "o",pch=10, xlab="Number of Variables",ylab= "R^2") 
plot(AIC,type = "o",pch=10, xlab="Number of Variables",ylab= "AIC") 
plot(AdjustedR,type = "o",pch=10, xlab="Number of Variables",ylab= "Adjusted R^2")
```
```{r}
reducedmodel1=lm(Weight.Change..lbs. ~ factor(Stress.Level) + Sleep.Quality + Duration..weeks. + Gender , data=weight)
summary(reducedmodel1)
```

```{r}
reducedmodel2=lm(Weight.Change..lbs. ~ Stress.Level + Sleep.Quality + Duration..weeks. + Gender + Physical.Activity.Level, data=weight)
summary(reducedmodel2)
```
```{r}
interacmodel1=lm(Weight.Change..lbs. ~ (factor(Stress.Level) + Sleep.Quality + Duration..weeks. + Gender)^2 , data=weight)
summary(interacmodel1)
```
```{r}
interacmodel2=lm(Weight.Change..lbs. ~ (factor(Stress.Level) + factor(Sleep.Quality) + Duration..weeks.)^2 , data=weight)
summary(interacmodel2)
```

```{r}
```


```{r}
interacmodel2=lm(Weight.Change..lbs. ~ (factor(Stress.Level) + factor(Sleep.Quality) + Duration..weeks.+factor(Stress.Level) * Duration..weeks.+ factor(Sleep.Quality)*Duration..weeks.) , data=weight)
summary(interacmodel2)
```

```{r}
ggplot(interacmodel2, aes(x=.fitted, y=.resid)) +
geom_point() +geom_smooth()+
geom_hline(yintercept = 0)
```